Add a Retriever module
Technoculture/personal-graph pull request #17
Opened 2024-04-09 08:54 UTC by anubhuti24

closes #16

2024-04-09 09:58 UTC, sutyum requested changes

2024-04-09 09:58 UTC, sutyum commented on scripts/retriever.py
> +from personal_graph.graph import Graph  # noqa: E402
why the noqa is required?

2024-04-09 09:58 UTC, sutyum commented on scripts/retriever.py
> +        passages = []
check and act on empty list query

2024-04-09 09:58 UTC, sutyum commented on scripts/retriever.py
> +    def retrieve(self, queries: Union[str, List[str]]) -> List[dotdict]:
a module has to have a forward method

2024-04-09 09:59 UTC, sutyum commented
- [ ] Add an example for the retriever
- [ ] Fix the implementation of natural language search used by the retriever

2024-04-10 12:04 UTC, anubhuti24 commented on scripts/retriever.py
> +    def retrieve(self, queries: Union[str, List[str]]) -> List[dotdict]:
Modified it

2024-04-12 04:44 UTC, sutyum requested changes

2024-04-12 04:44 UTC, sutyum commented on personal_graph/database.py
> +    node_or_edge: Tuple[Any], node_or_edge_type: str
probably need a Union type here

2024-04-12 04:44 UTC, sutyum commented on personal_graph/models.py
>      attribute: Union[str, Dict[str, str]] = Field(
should be 'attributes'

2024-04-12 07:50 UTC, anubhuti24 commented on personal_graph/database.py
> +    node_or_edge: Tuple[Any], node_or_edge_type: str
Updated it to use Union type

2024-04-12 08:51 UTC, anubhuti24 commented on personal_graph/models.py
>      attribute: Union[str, Dict[str, str]] = Field(
Modified

2024-04-12 10:28 UTC, sutyum requested changes

2024-04-12 10:28 UTC, sutyum commented on scripts/retriever.py
this is not meant to be a script, should go in personal_graph dir

2024-04-12 10:28 UTC, sutyum commented on scripts/retriever.py
> +class Retriever(dspy.Retrieve):
Better to name it in a manner similar to other RMs in DSPy: PersonalRM

2024-04-12 10:28 UTC, sutyum commented on scripts/retriever.py
> +        self, query_or_queries: Union[str, List[str]], k: Optional[int] = None, **kwargs
add a TODO comment to use the value of k in the future

2024-04-12 10:30 UTC, sutyum requested changes

2024-04-12 10:30 UTC, sutyum commented on examples/low_level_api.py
> +sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
why is this needed?

2024-04-12 10:53 UTC, sutyum approved these changes

2024-04-12 10:53 UTC, merged

2024-04-12 15:12 UTC, sutyum commented on examples/low_level_api.py
> +sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
not needed, ill explain